[manifest]
version = "1.0.0"
dump_lua = true
priority = 42042

# This also accounts for Paya's Terrible Addons, which does something similar.
[[patches]]
[patches.regex]
target = 'functions/state_events.lua'
pattern = '''math\.floor\(MadLib\.get_full_score\(hand_chips,mult\)\)'''
position = 'at'
payload = '''math.floor(MadLib.get_full_score(hand_chips,mult,pow))'''
match_indent = true
times = 10

# This also accounts for Paya's Terrible Addons, which does something similar.
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/ui.lua"]'
pattern = '''  local new_mult_text = number_format(G.GAME.current_round.current_hand[e.config.type] or SMODS.Scoring_Parameters[e.config.type].default_value)'''
position = 'at'
payload = '''local new_mult_text = number_format(G.GAME.current_round.current_hand[e.config.type] 
  or SMODS.Scoring_Parameters[e.config.type].default_value)
'''
match_indent = true

# This also accounts for Paya's Terrible Addons, which does something similar.
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''hand_chips = mod_chips(0)'''
position = 'after'
payload = '''pow = mod_pow(1)'''
match_indent = true